def stageStatus = [:]

pipeline {
    agent any

    parameters {
        string(name: 'PROJECT_PATH', defaultValue: 'Ze-dos-Livros/projetoc14', description: 'Caminho do projeto')
        string(name: 'MAVEN_TOOL', defaultValue: 'Maven3', description: 'Ferramenta Maven a usar')
    }

    stages {

        stage('Checkout') {
            steps {
                echo "Clonando repositório..."
                checkout scm
            }
            post {
                success { script { stageStatus['Checkout'] = 'SUCCESS' } }
                failure { script { stageStatus['Checkout'] = 'FAILED' } }
            }
        }

        stage('Load Utils'){
                steps{
                    script{
                        utils = load 'projetoc14/utils.groovy'
                    }
                }
            }

        stage('Build Once') {
            steps {
                echo "Buildando o projeto apenas uma vez"
                dir('projetoc14') {
                    sh "rm -rf target || true"
                    sh "mvn clean install -DskipTests"
                }
            }
        }

        stage('Parallel Tests') {
            parallel {
                stage('Test') {
                    steps {
                        echo "Executando testes unitários..."
                        dir('projetoc14') {
                            sh "mvn -Dtest=**/implementacao/*Test.java test"
                        }
                    }
                    post {
                        always {
                            junit 'projetoc14/target/surefire-reports/*.xml'
                            archiveArtifacts artifacts: 'projetoc14/target/surefire-reports/*', fingerprint: true
                        }
                        success { script { stageStatus['Test'] = 'SUCCESS' } }
                        failure { script { stageStatus['Test'] = 'FAILED' } }
                    }
                }
                stage('Integration Test') {
                    steps {
                        echo "Executando testes de integração..."
                        dir('projetoc14') {
                            sh "mvn -Dtest=**/controller/*Test.java test"
                        }
                    }
                    post {
                        always {
                            dir('projetoc14') {
                                junit 'target/surefire-reports/*.xml'
                                archiveArtifacts artifacts: 'target/surefire-reports/*', fingerprint: true
                            }
                        }
                        success { script { stageStatus['Integration Test'] = 'SUCCESS' } }
                        failure { script { stageStatus['Integration Test'] = 'FAILED' } }
                    }
                }
            }
        }

        stage('Generate Coverage'){
            steps {
                script {
                    utils.generateCoverage(stageStatus, this)
                }
            }
        }
        stage('Build') {
            steps {
                echo "Empacotando JAR..."
                dir('projetoc14') {
                    sh "${tool 'Maven3'}/bin/mvn -B package"
                }
            }
            post {
                success {
                    dir('projetoc14') {
                        archiveArtifacts artifacts: 'target/*.jar', fingerprint: true
                    }
                    script { stageStatus['Build'] = 'SUCCESS' }
                }
                failure { script { stageStatus['Build'] = 'FAILED' } }
            }
        }
    }

    post {

        failure {
            script {
                utils.sendStatusEmail("FAILED ❌", stageStatus, this)
            }
        }

        success {
            script {
                utils.sendStatusEmail("SUCCESS ✅", stageStatus, this)
            }
        }
    }
}