name: Pipeline CI/CD

on:
  push:
    branches: [ main ]
  release:
    types: [ created ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Instalar Java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Executar testes unitários
        working-directory: projetoc14
        run: mvn test

      - name: Salvar relatórios de teste
        uses: actions/upload-artifact@v4
        with:
          name: relatorio-testes
          path: projetoc14/target/surefire-reports
